### ISSUE TITLE
Throws errors or warnings on perl 5.39.x

### ISSUE THREAD

**Issue by haarg** [gryphonshafer/Log-Dispatch-Email-Mailer#5]
The line `use exact 'Log::Dispatch::Email';` throws errors (on perl 5.39.1) or deprecation warnings (on 5.39.2+) for development perl versions. This is because it results in a call like `Log::Dispatch::Email->import('Log::Dispatch::Email::Mailer')` via exact.pm. The new UNIVERSAL::import method complains about the unhandled argument.

This is a result of the behavior of exact.pm: gryphonshafer/exact#4

**Comment by gryphonshafer** [comment]
Thanks for the report. I've been away on vacation, but I'll try to address this issue this week.
